language: clojure
branches:
  only:
    - master
    - release
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/72def5309f8285005b0c
    on_success: change
    on_failure: always
    on_start: false
